@host=http://localhost:5000/api
@contentType=Content-Type: application/json
###
POST {{host}}/auth/photographer/register
Content-Type: application/json

{
    "name":"hareesh",
    "email":"madahareesh12@gmail.com",
    "username":"hareesh",
    "password":"1234567890",
    "purpose":"register"
}
###

POST {{host}}/auth/photographer/resend
Content-Type: application/json

{
    "email":"madahareesh12@gmail.com",
    "purpose":"resend"
}

###

POST {{host}}/auth/photographer/verify
Content-Type: application/json

{
    "email":"madahareesh12@gmail.com",
    "otp":"846244"
}

###
POST {{host}}/auth/photographer/reset
Content-Type: application/json

{
    "email":"madahareesh12@gmail.com",
    "purpose":"reset"
}
###
PUT {{host}}/auth/photographer/verify
Content-Type: application/json

{
    "email":"madahareesh12@gmail.com",
    "otp":"943308",
    "password":"741852963"
}

###

POST {{host}}/auth/photographer/login
Content-Type: application/json

{
    "email":"madahareesh12@gmail.com",
    "password":"741852963",
    "userType":"photographer"
}

###

POST {{host}}/auth/customer/register
Content-Type: application/json

{
    "email":"chennanagarjuna3777@gmail.com",
    "name":"nagarjuna",
    "password":"789456",
    "userType":"customer",
    "purpose":"register"
}
###

POST {{host}}/auth/customer/verify
{{contentType}}

{
    "email":"chennanagarjuna3777@gmail.com",
    "otp":"957543",
    "userType":"customer"

}
###

POST {{host}}/auth/customer/login
{{contentType}}

{
    "email":"chennanagarjuna3777@gmail.com",
    "password":"789456",
    "userType":"customer"
}